#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -rf processor*
rm -rf log*
rm -rf postProcessing/
rm -rf acousticData/
rm -rf res.foam

#------------------------------------------------------------------------------
