#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0
rm -rf acousticData/
rm -rf successful.txt
rm -rf failed.txt
rm -rf total.log

#------------------------------------------------------------------------------
