#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

errors=0

echo $'===== Running All Tests =====\n'> summary.log
echo $'===== Running All Tests =====\n'> total.log

cd unit/testExpiredFunction/
testExpiredFunction &>> ../../total.log
rc=$?
if [ "$rc" = "0" ]; then
    echo $'===== testExpiredFunction		OK =====\n' >> ../../summary.log
else
    errors=$errors+1
    echo $'===== testExpiredFunction		FAILED =====\n' >> ../../summary.log
fi
cd ../testValueAt/
testValueAt &>> ../../total.log
rc=$?
if [ "$rc" = "0" ]; then
    echo $'===== testValueAt		OK =====\n' >> ../../summary.log
else
    errors=$errors+1
    echo $'===== testValueAt		FAILED =====\n' >> ../../summary.log
fi
cd ../../integration/testFormulationFunctions/
testFormulationFunction &>> ../../total.log
rc=$?
if [ "$rc" = "0" ]; then
    echo $'===== testFormulationFunctions		OK =====\n' >> ../../summary.log
else
    errors=$errors+1
    echo $'===== testFormulationFunctions		FAILED =====\n' >> ../../summary.log
fi
cd ../../integration/testMonopoleSource/
testMonopoleSource &>> ../../total.log
rc=$?
if [ "$rc" = "0" ]; then
    echo $'===== testMonopoleSource		OK =====\n' >> ../../summary.log
else
    errors=$errors+1
    echo $'===== testMonopoleSource		FAILED =====\n' >> ../../summary.log
fi
cd ../../integration/testDipoleSource/
testDipoleSource &>> ../../total.log
rc=$?
if [ "$rc" = "0" ]; then
    echo $'===== testDipoleSource		OK =====\n' >> ../../summary.log
else
    errors=$errors+1
    echo $'===== testDipoleSource		FAILED =====\n' >> ../../summary.log
fi
cd ../../
if [ "$errors" = "0" ]; then
    echo $errors > successful.txt
else
    echo $errors > failed.txt
fi 

#------------------------------------------------------------------------------
