#!/bin/bash

if [ $# -eq 0 ]
then
    PATH_TO_SCRIPT=$PWD/allCodeToOneFile
    THIS_DIR=$PWD
    OUT_FILE=$PWD/allCode
    export PATH_TOSCRIPT
else
    PATH_TO_SCRIPT=$1
    THIS_DIR=$2
    OUT_FILE=$3
fi

ALL_FILES=`ls $THIS_DIR`

for CFILE in $ALL_FILES
do
    if [ -d "$THIS_DIR/$CFILE" ]
    then
        $PATH_TO_SCRIPT $PATH_TO_SCRIPT "$THIS_DIR/$CFILE" "$OUT_FILE"
    else
        GRES=`echo $CFILE | grep ".H"`
        if [ "$GRES" = "$CFILE" ]
        then
            cat $THIS_DIR/$CFILE >> $OUT_FILE
            echo " " >> $OUT_FILE
        fi
        #
        GRES=`echo $CFILE | grep ".C"`
        if [ "$GRES" = "$CFILE" ]
        then
            cat $THIS_DIR/$CFILE >> $OUT_FILE
            echo " " >> $OUT_FILE
        fi
        #
        GRES=`echo $CFILE | grep ".py"`
        if [ "$GRES" = "$CFILE" ]
        then
            cat $THIS_DIR/$CFILE >> $OUT_FILE
            echo " " >> $OUT_FILE
        fi
    fi
done

#
#END-OF-FILE
#

