#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf processor*
rm -rf acousticData
rm -rf postProcessing
rm -rf log.*

# ----------------------------------------------------------------- end-of-file
