#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication mirrorMesh -noFunctionObjects

# Get application directory
#application=`getApplication`

#runApplication "$application"


# ----------------------------------------------------------------- end-of-file
