#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.orig 0

runApplication blockMesh

runApplication mirrorMesh -noFunctionObjects -overwrite

runApplication decomposePar
# Get application directory

application=`getApplication`

runApplication mpirun -np 8 $application -parallel

runApplication reconstructPar


# ----------------------------------------------------------------- end-of-file
