#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication mirrorMesh -noFunctionObjects

runApplication decomposePar
# Get application directory
application=`getApplication`
runApplication mpirun -np 12 $application -parallel

runApplication reconstructPar


# ----------------------------------------------------------------- end-of-file
