#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf pressureData
rm -rf complexPressureData
rm -rf surfaceGeometryData

rm -rf constant/polyMesh
rm -rf acousticData
rm -rf dipole3D.foam

# ----------------------------------------------------------------- end-of-file
