#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -rf constant/polyMesh0 constant/polyMesh

runApplication decomposePar

# Get application directory
application=`getApplication`

runApplication mpirun -np 8 $application -parallel
#runApplication mpirun -np 96 -hostfile $PBS_NODEFILE $application -parallel

runApplication reconstructPar -latestTime

touch dipole3D.foam

# ----------------------------------------------------------------- end-of-file